# Generated by Django 3.0.6 on 2020-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
